
spring:
  application:
    name: SwappeeApplication
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/swappee
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: false
    hibernate.ddl-auto: update
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non-null

server:
  servlet:
    context-path: /swappee
  error:
    include-stacktrace: never
  port: 8022

jwt:
  signing-key-secret: mySecret
  token-expiration-in-seconds: 604800

frontend:
  baseurl: http://localhost:3000

elasticsearch:
  baseurl: http://localhost:9200

logging:
  file: logs/SwappeeApplication.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.cloud.openfeign: INFO
    org.hibernate: INFO
    com.swappee: DEBUG